# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'qoc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qoc
  pod 'SwiftGen', '~>3.0.1'

  target 'qocTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'qocUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
